version: '3.9'

services:
  backend:
    build: .
    container_name: nest-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - nest-network

  db:
    image: postgres:15
    container_name: nest-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: PagosQR
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - nest-network

volumes:
  db-data:

networks:
  nest-network:
